# Site settings
title: 重生云
author: Chopin
description: "明月装饰了你的窗，你装饰了别人的梦。"
encoding: utf-8
markdown: kramdown
url: https://xiaochopin.github.io
baseurl: /
permalink: /:categories/:year/:month/:day/:title
future: true
# Menu
menu:
  - menu.md
  - about.md
# Contact Icons
contact:
  - link: https://blogscn.fun/
    icon: fa-bold
  - link: /feed.xml
    icon: fa-rss
  - link: mailto:xiaochopin@foxmail.com
    icon: fa-envelope-o
  - link: https://github.com/xiaochopin
    icon: fa-github
# GitHub Repo for your site
issue_report:
  github: xiaochopin/xiaochopin.github.io
# Exclusion
exclude:
  - Rakefile
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md

plugins:
  - jekyll-seo-tag

defaults:
  - scope:
      path: ""
    values:
      image: /favicon.ico

compress_html:
  clippings:      all
  comments:       ["<!--", "-->"]
  endings:        all
  startings:      [html, head, body]