# Site settings
title: 重生云
author: Chopin
description: "明月装饰了你的窗，你装饰了别人的梦。"
encoding: utf-8
markdown: kramdown
url: https://xiaochopin.github.io
baseurl: /
permalink: /:categories/:year/:month/:day/:title
future: true
# Menu
menu:
  - menu.md
  - about.md
# Contact Icons
contact:
  - link: https://blogscn.fun/
    icon: fa-bold
    title: 笔墨迹
  - link: /feed.xml
    icon: fa-rss
    title: RSS订阅
  - link: mailto:xiaochopin@foxmail.com
    icon: fa-envelope-o
    title: 给我发邮件
  - link: https://github.com/xiaochopin
    icon: fa-github
    title: GitHub主页
# GitHub Repo for your site
issue_report:
  github: xiaochopin/xiaochopin.github.io
# Exclusion
exclude:
  - Rakefile
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md

plugins:
  - jekyll-seo-tag
  - jekyll-minifier

defaults:
  - scope:
      path: ""
    values:
      image: /favicon.ico

jekyll-minifier:
  exclude: 'about.md'
  exclude: 'feed.xml'
  preserve_php: true
  remove_spaces_inside_tags: false
  remove_multi_spaces: false
  remove_comments: true
  remove_intertag_spaces: false
  remove_quotes: false
  compress_css: true
  compress_javascript: true
  compress_json: true
  simple_doctype: false
  remove_script_attributes: false
  remove_style_attributes: false
  remove_link_attributes: false
  remove_form_attributes: false
  remove_input_attributes: false
  remove_javascript_protocol: false
  remove_http_protocol: false
  remove_https_protocol: false
  preserve_line_breaks: false
  simple_boolean_attributes: false
  compress_js_templates: false
  preserve_patterns: []
  terser_args: []